### ISSUE TITLE
Sequence of bytes deflate issue

### ISSUE THREAD

**Issue by maca** [folkertdev/elm-flate#1]
Hi,

I am using elm-flate for an elm PNG decoder/encoder I am trying to implement, but I might be having an issue with deflateZlib. 

I have a sequence of bytes corresponding to the image data, each line of the image is composed from an 8bit int idicating a filtering method and n (8bit * number of channels) pixels.

If I deflate those `Bytes` using deflateZlib and immediately inflate them using inflateZlib I get `Nothing` instead of the same `Bytes`:

https://github.com/maca/elm-png/blob/encoding/src/Png.elm#L137

Reproducing it's only matter of cloning the repo, running the reactor, visiting Main.elm and uploading this image: 

http://www.schaik.com/pngsuite/f00n2c08.png

This image is from PNG suite test images, and it will correctly decode.
Decoding currently only works for 8bit per channel images.

Thanks for the lib :)

**Comment by folkertdev** [comment]
Thanks for this. I extracted the image data and now have a failing test case. The error is really in the vanilla deflate implementation, which makes this a harder problem. I'll have time to look into it further at the end of the week.

**Comment by folkertdev** [comment]
this issue is fixed in version 2.0.1

There was a bug in lz77 where some values were incorrectly bitmasked, leading to invalid matches. Somehow, testing with text documents didn't catch this. 

Thanks again for opening this issue.

**Comment by maca** [comment]
thank you! I've just updated and it seems to be working fine :)
