### ISSUE TITLE
Deflate output is invalid for inputs >=1MB

### ISSUE THREAD

**Issue by damienprystay** [folkertdev/elm-flate#3]
Hello!

Given a sequence of 1,048,576 or more bytes, `deflate` (with an `Encoding` other than `Raw`) produces a result that can't be re-inflated.

```elm
-- shorthand for encoding a string to bytes, deflating them, then re-inflating them
> deflateInflate =
|   Bytes.Encode.string >> Bytes.Encode.encode >> Debug.log "original"
|   >> Flate.deflate >> Debug.log "deflated"
|   >> Flate.inflate >> Debug.log "reinflated"

-- just under 1MB: returns the input
> String.repeat (1024*1024-1) "a" |> deflateInflate
original: <1048575 bytes>
deflated: <1541 bytes>
reinflated: Just <1048575 bytes>

-- at 1MB or multiples thereof: returns empty "success"
> String.repeat (1024*1024) "a" |> deflateInflate
original: <1048576 bytes>
deflated: <12 bytes>
reinflated: Just <0 bytes>

-- above 1MB: fails to re-inflate
> String.repeat (1024*1024+1) "a" |> deflateInflate
original: <1048577 bytes>
deflated: <1554 bytes>
reinflated: Nothing
```

I've confirmed that this isn't an issue with the _inflate_ step by successfully using `inflate` on more than 1MB of externally-deflated data; I've also seen that the output of `deflate` in these >1MB cases can't be re-inflated by external programs (e.g. `gunzip`). (Also I originally encountered this behaviour in-browser, so it isn't just some limitation of elm-repl.)

I had a brief look at the source, but didn't see any indication that this is a deliberate or explicit limitation of the library or algorithm; apologies if it is and I just missed it.

Thanks!

(Elm 0.19.1, Flate 2.0.3)

**Comment by folkertdev** [comment]
Thank's for this issue!

I quickly found the two issues: in incorrect comparison operator (`>` instead of `>=`) and the incorrect flushing of blocks (should not flush between blocks, only after all blocks have been written).

version 2.0.4 with this issue fixed has been published

**Comment by damienprystay** [comment]
Fantastic, thank you for the very quick fix!
